# Generated by Django 3.0 on 2019-12-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('marks', models.FloatField()),
                ('addr', models.CharField(max_length=100)),
            ],
        ),
    ]
